source "http://rubygems.org"
gem 'rails', '2.3.5'
gem 'bundler'
gem 'rspec'
gem 'rspec-rails'
gem 'cucumber'
gem 'cucumber-rails'
gem 'database_cleaner'
gem 'webrat'
gem 'selenium-client'
gem 'rack'
gem 'test-unit', '1.2.3'
gem 'sqlite3-ruby'
gem 'ZenTest'
gem 'authlogic'
gem 'nifty-generators'
gem 'factory_girl'
gem 'acts-as-taggable-on', '>=2.0.0.rc1'
gem 'easy_roles'
gem 'paperclip'
#gem 'ruby-debug19'
gem 'ruby-debug'