#!/bin/bash

sudo yum install gcc
sudo yum install git-core
sudo yum install ruby-irb
sudo yum install rubygems
sudo yum install ruby-devel
sudo yum install libxml
sudo yum install libxml2
sudo yum install libxslt-devel
sudo yum install mysql
sudo yum install ruby-mysql
sudo yum install mysql-devel
sudo yum install sqlite-devel
sudo yum install java-1.6.0-openjdk

sudo gem install bundler
bundle install

if [[ ! -d "${HOME}/bin" ]] 
then
	mkdir "${HOME}/bin"
fi
wget --no-check-certificate -O ~/bin/lein https://github.com/technomancy/leiningen/raw/stable/bin/lein
chmod ugo+x ~/bin/lein

cd recomendation-engine
echo $PWD
lein deps
