#!/bin/bash

#PWD needs to be in recomendation-engine/ for the correct class path
if [[ ! $PWD == *"recomendation-engine" ]]
then
  cd recomendation-engine
fi

# Make sure $RAILS_ENV is set
if [[ -z $RAILS_ENV ]]
then
  export RAILS_ENV='development'
fi

pidpath="../tmp/pids/${RAILS_ENV}/recomendation-server.pid"

if [ -f "${pidpath}" ]
then
  pid=`cat ${pidpath}`
  if kill $pid
  then
    echo "Killed"
    rm -f $pidpath
    exit 0
  else
    echo "The pid $pid started with recomendation-engine/start is not running. Nothing to stop"
    exit 0
  fi
else
  echo "There is no server that was started with recomendation-engine/start"
  exit 0
fi

