#!/bin/bash

#PWD needs to be in recomendation-engine/ for the correct class path
if [[ ! $PWD == *"recomendation-engine" ]]
then
  cd recomendation-engine
fi

if [ -f '.server.pid' ]
then
  pid=`cat .server.pid`
  if kill $pid
  then
    echo "Killed"
    rm -f '.server.pid'
    exit 0
  else
    echo "The pid $pid started with recomendation-engine/start is not running. Nothing to stop"
    exit 0
  fi
else
  echo "There is no server that was started with recomendation-engine/start"
  exit 0
fi

