work_dir: tmp/work

demo_exercise_titles:
  - Test
  - t
  - Remove A Char From A String

rating_values:
  too_hard: 1
  too_easy: 2
  good_challenge: 3

recomendation_server_uri:
  production: "http://127.0.0.1:8080/"
  staging: "http://127.0.0.1:8081/"
  test: "http://127.0.01:8082/"
  cucumber: "http://127.0.0.1:8082/"
  development: "http://127.0.0.1:8083/"
